name: release-test

on:
  pull_request:
    paths:
      - .github/workflows/release-test.yaml
      - .goreleaser.yaml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --snapshot --skip-publish --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
